FROM python:3.12-slim

LABEL maintainer="HNG DevSecOps"
LABEL description="HNG Anomaly Detection / DDoS Detection Engine"

RUN apt-get update && apt-get install -y --no-install-recommends \
    iptables \
    curl \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY main.py monitor.py baseline.py detector.py blocker.py \
     unbanner.py notifier.py dashboard.py ./


COPY config.yaml .

RUN mkdir -p /var/log/detector

EXPOSE 8080

USER root

CMD ["python", "-u", "main.py"]